'use client';

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, Bell, ChevronDown, Download, Eye, FileUp, Filter, Plus, Search, ShieldCheck, Sparkles, Wallet, X } from 'lucide-react';

type Transaction = { id:string; date:string; merchant:string; company:string; category:string; amount:number; recurring?:boolean };
const palette:Record<string,string>={Housing:'#ffb39a',Tax:'#22231f',Savings:'#baf269',Food:'#f3dc77',Subscriptions:'#cbb8f5',Transport:'#bed8f5',Health:'#ef9dba',Shopping:'#edb976',Other:'#b9bcb3'};
const seed:Transaction[]=[
 {id:'1',date:'2026-09-02',merchant:'Monthly rent',company:'Harbor Properties',category:'Housing',amount:1680,recurring:true},
 {id:'2',date:'2026-09-03',merchant:'Savings transfer',company:'Up Bank Saver',category:'Savings',amount:1024,recurring:true},
 {id:'3',date:'2026-09-05',merchant:'Woolworths Metro',company:'Woolworths Group',category:'Food',amount:142.45},
 {id:'4',date:'2026-09-07',merchant:'Opal top up',company:'Transport NSW',category:'Transport',amount:80},
 {id:'5',date:'2026-09-09',merchant:'iCloud+',company:'Apple',category:'Subscriptions',amount:14.99,recurring:true},
 {id:'6',date:'2026-09-11',merchant:'Chemist Warehouse',company:'Sigma Healthcare',category:'Health',amount:68.20},
 {id:'7',date:'2026-09-13',merchant:'Netflix',company:'Netflix',category:'Subscriptions',amount:25.99,recurring:true},
 {id:'8',date:'2026-09-15',merchant:'Woolworths Metro',company:'Woolworths Group',category:'Food',amount:108.72},
 {id:'9',date:'2026-09-18',merchant:'Dinner',company:'Merivale',category:'Food',amount:92.40},
 {id:'10',date:'2026-09-21',merchant:'Mobile plan',company:'Telstra',category:'Subscriptions',amount:62,recurring:true},
];
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n);

export default function Home(){
 const[view,setView]=useState<'overview'|'transactions'|'insights'>('overview'); const[income,setIncome]=useState(6420); const[tax,setTax]=useState(1412); const[tx,setTx]=useState<Transaction[]>(seed); const[ready,setReady]=useState(false); const[modal,setModal]=useState(false); const[query,setQuery]=useState(''); const[category,setCategory]=useState('All'); const[toast,setToast]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem('moneygraph-data');if(raw){const d=JSON.parse(raw);setIncome(d.income??6420);setTax(d.tax??1412);setTx(d.transactions??seed)}}finally{setReady(true)}},[]);
 useEffect(()=>{if(ready)localStorage.setItem('moneygraph-data',JSON.stringify({income,tax,transactions:tx}))},[income,tax,tx,ready]);
 const stats=useMemo(()=>{const spend=tx.reduce((s,t)=>s+t.amount,0)+tax;const saved=tx.filter(t=>t.category==='Savings').reduce((s,t)=>s+t.amount,0);const byCat=Object.entries(tx.reduce((a,t)=>(a[t.category]=(a[t.category]||0)+t.amount,a),{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]);const byCo=Object.entries(tx.reduce((a,t)=>(a[t.company]=(a[t.company]||0)+t.amount,a),{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]);const disposable=Math.max(0,income-tax);const top4=byCo.slice(0,4).reduce((s,x)=>s+x[1],0);return{spend,saved,disposable,remaining:income-spend,byCat,byCo,top4,concentration:disposable?Math.round(top4/disposable*100):0}},[tx,income,tax]);
 const filtered=tx.filter(t=>(category==='All'||t.category===category)&&(`${t.merchant} ${t.company}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date));
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2600)};
 function addTransaction(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item:Transaction={id:crypto.randomUUID(),date:String(f.get('date')),merchant:String(f.get('merchant')),company:String(f.get('company')),category:String(f.get('category')),amount:Number(f.get('amount')),recurring:f.get('recurring')==='on'};setTx(v=>[...v,item]);setModal(false);notify('Transaction added and graph recalculated.');}
 function importCsv(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;file.text().then(text=>{const rows=text.trim().split(/\r?\n/).slice(1);const parsed=rows.map((r,i)=>{const [date,merchant,company,cat,amount]=r.split(',').map(x=>x.trim().replace(/^"|"$/g,''));return{id:crypto.randomUUID(),date,merchant,company:company||merchant,category:palette[cat]?cat:'Other',amount:Math.abs(Number(amount)),recurring:false} as Transaction}).filter(x=>x.date&&x.merchant&&Number.isFinite(x.amount));if(parsed.length){setTx(v=>[...v,...parsed]);notify(`${parsed.length} transactions imported.`)}else notify('No valid rows found. Use date, merchant, company, category, amount.')});e.target.value=''}
 function exportCsv(){const out=['date,merchant,company,category,amount',...tx.map(t=>[t.date,t.merchant,t.company,t.category,t.amount].join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download='moneygraph-transactions.csv';a.click();URL.revokeObjectURL(a.href);}
 return <main>{toast&&<div className="toast"><ShieldCheck size={17}/>{toast}</div>}<header className="topbar"><button className="brand" onClick={()=>setView('overview')}><span className="brand-mark"><i/><i/><i/></span>MoneyGraph</button><nav>{(['overview','insights','transactions'] as const).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</nav><div className="header-actions"><span className="privacy"><ShieldCheck size={14}/> Local & private</span><button aria-label="Notifications"><Bell size={18}/><i/></button><span className="avatar">SM</span></div></header>
 <section className="page-shell">
 {view==='overview'&&<><div className="title-row"><div><p className="eyebrow">YOUR MONEY, MAPPED</p><h1>Follow the dollar.</h1><p>Based on {tx.length} transactions stored only in this browser.</p></div><div className="controls"><button className="month-button">September 2026<ChevronDown size={15}/></button><label className="import-button"><FileUp size={16}/>Import CSV<input type="file" accept=".csv,text/csv" onChange={importCsv}/></label><button className="connect-button" onClick={()=>setModal(true)}><Plus size={17}/>Add transaction</button></div></div>
 <section className="summary-grid"><article><span>Income <button onClick={()=>{const v=prompt('Monthly take-home income',String(income));if(v&&Number(v)>0)setIncome(Number(v))}}>edit</button></span><strong>{money(income)}</strong><small><ArrowDownRight size={14}/> Monthly take-home pay</small></article><article><span>Available after tax</span><strong>{money(stats.disposable)}</strong><small>{income?Math.round(stats.disposable/income*100):0}% of income</small></article><article className="saved-card"><span>Remaining this month</span><strong className={stats.remaining<0?'negative':''}>{money(stats.remaining)}</strong><small>{stats.saved?money(stats.saved)+' moved to savings':'No savings recorded'}</small><div className="progress-ring" style={{'--p':`${Math.min(100,Math.max(0,stats.spend/income*100))}%`} as React.CSSProperties}><b>{Math.round(stats.spend/income*100)}%</b></div></article></section>
 <section className="workspace-grid"><article className="graph-card"><div className="card-head"><div><p className="eyebrow">LIVE MONEY FLOW</p><h2>Your September dollar</h2></div><span className="live-pill"><i/>Calculated live</span></div><div className="legend"><span>Income</span><span>Categories</span><span>Destinations</span></div><DynamicGraph income={income} categories={stats.byCat} companies={stats.byCo}/><p className="graph-note"><Eye size={15}/> Paths are sized from the transactions in this browser.</p></article><aside className="right-rail"><Concentration stats={stats}/><Breakdown categories={stats.byCat} income={income}/></aside></section></>}
 {view==='transactions'&&<Transactions items={filtered} all={tx} query={query} setQuery={setQuery} category={category} setCategory={setCategory} onAdd={()=>setModal(true)} onImport={importCsv} onExport={exportCsv} onDelete={id=>setTx(v=>v.filter(t=>t.id!==id))}/>} 
 {view==='insights'&&<Insights stats={stats} transactions={tx} income={income} tax={tax} setTax={setTax}/>} 
 </section>{modal&&<AddModal onClose={()=>setModal(false)} onSubmit={addTransaction}/>}</main>;
}

function DynamicGraph({income,categories,companies}:{income:number;categories:[string,number][];companies:[string,number][]}){const cats=categories.slice(0,5);const cos=companies.slice(0,5);const[active,setActive]=useState<string|null>(null);return <div className="money-map dynamic"><svg viewBox="0 0 900 340" preserveAspectRatio="none">{cats.map(([label,value],i)=>{const y=38+i*66,color=palette[label]||palette.Other,w=Math.max(7,Math.min(27,value/income*95));return <g key={label} onMouseEnter={()=>setActive(label)} onMouseLeave={()=>setActive(null)}><path d={`M 140 168 C 235 168,220 ${y},338 ${y}`} fill="none" stroke={color} strokeWidth={w} opacity={active&&active!==label?.16:.76}/><circle cx="400" cy={y} r={25} fill={color} stroke="#171914"/><text x="400" y={y+4} textAnchor="middle" className="node-index">{i+1}</text><text x="442" y={y-2} className="svg-name">{label}</text><text x="442" y={y+14} className="svg-value">{money(value)}</text></g>})}{cos.map(([label,value],i)=>{const y=38+i*66,color=['#ffb39a','#baf269','#f3dc77','#cbb8f5','#bed8f5'][i];return <g key={label}><path d={`M 525 ${y} C 600 ${y},610 ${y},675 ${y}`} fill="none" stroke={color} strokeWidth={Math.max(6,Math.min(21,value/income*85))} opacity=".58"/><circle cx="713" cy={y} r="22" fill="#fffdf8" stroke={color} strokeWidth="5"/><text x="751" y={y-2} className="svg-name">{label.length>20?label.slice(0,18)+'…':label}</text><text x="751" y={y+14} className="svg-value">{money(value)}</text></g>})}<circle cx="103" cy="168" r="49" fill="#171914"/><text x="103" y="160" textAnchor="middle" className="salary-label">INCOME</text><text x="103" y="181" textAnchor="middle" className="salary-value">{money(income)}</text></svg></div>}
function Concentration({stats}:{stats:any}){return <article className="insight-card"><div className="spark"><Sparkles size={18}/></div><p className="eyebrow">CONCENTRATION SIGNAL</p><h2><em>{stats.concentration}%</em> of disposable income reaches your top four companies.</h2><div className="rank-list">{stats.byCo.slice(0,4).map(([n,v]:[string,number],i)=><div key={n}><span>{i+1}</span><b>{n}</b><small>{money(v)}</small></div>)}</div><p className="explain">Calculated from merchant ownership and destination totals in your records.</p></article>}
function Breakdown({categories,income}:{categories:[string,number][],income:number}){return <article className="breakdown-card"><div className="card-head"><div><p className="eyebrow">BREAKDOWN</p><h2>Where it went</h2></div><Wallet size={20}/></div><div className="flow-list">{categories.slice(0,6).map(([n,v])=><div key={n}><span className="dot" style={{background:palette[n]||palette.Other}}/><span>{n}</span><b>{money(v)}</b><small>{Math.round(v/income*100)}%</small></div>)}</div></article>}
function Transactions({items,all,query,setQuery,category,setCategory,onAdd,onImport,onExport,onDelete}:any){return <><div className="section-title"><div><p className="eyebrow">LEDGER</p><h1>Transactions</h1><p>{all.length} records · edits update every graph and insight</p></div><div className="controls"><label className="import-button"><FileUp size={16}/>Import CSV<input type="file" accept=".csv" onChange={onImport}/></label><button className="month-button" onClick={onExport}><Download size={16}/>Export</button><button className="connect-button" onClick={onAdd}><Plus size={16}/>Add</button></div></div><article className="ledger"><div className="ledger-tools"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merchant or company…"/></label><label><Filter size={16}/><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{Object.keys(palette).map(x=><option key={x}>{x}</option>)}</select></label></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Merchant</th><th>Ultimate company</th><th>Category</th><th>Amount</th><th/></tr></thead><tbody>{items.map((t:Transaction)=><tr key={t.id}><td>{new Date(t.date+'T00:00').toLocaleDateString('en-AU',{day:'2-digit',month:'short'})}</td><td><b>{t.merchant}</b>{t.recurring&&<small>Recurring</small>}</td><td>{t.company}</td><td><span className="category-pill"><i style={{background:palette[t.category]||palette.Other}}/>{t.category}</span></td><td><b>{money(t.amount)}</b></td><td><button aria-label="Delete" onClick={()=>onDelete(t.id)}><X size={15}/></button></td></tr>)}</tbody></table>{!items.length&&<div className="empty">No transactions match these filters.</div>}</div></article></>}
function Insights({stats,transactions,income,tax,setTax}:any){const recurring=transactions.filter((t:Transaction)=>t.recurring);const annual=recurring.reduce((s:number,t:Transaction)=>s+t.amount,0)*12;return <><div className="section-title"><div><p className="eyebrow">DEPENDENCY ANALYSIS</p><h1>Your financial signals</h1><p>Patterns derived from the records you have added.</p></div></div><div className="insights-grid"><article className="big-signal"><span>01 / CONCENTRATION</span><h2>Your top four destinations receive <em>{money(stats.top4)}</em> each month.</h2><p>{stats.concentration}% of disposable income. A higher share means fewer companies have more influence over your cost of living.</p></article><article><span>02 / FIXED COST</span><strong>{money(annual)}</strong><h3>Annual recurring commitments</h3><p>{recurring.length} recurring payments identified.</p></article><article><span>03 / BUFFER</span><strong>{stats.remaining>0?(stats.spend?Math.round(stats.remaining/(stats.spend/30)):0):0} days</strong><h3>Surplus runway</h3><p>Based on this month’s average daily outflow.</p></article><article className="tax-card"><span>04 / TAX</span><strong>{money(tax)}</strong><h3>Monthly tax estimate</h3><button onClick={()=>{const v=prompt('Monthly tax amount',String(tax));if(v&&Number(v)>=0)setTax(Number(v))}}>Adjust estimate</button></article></div></>}
function AddModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onSubmit={onSubmit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">NEW RECORD</p><h2>Add transaction</h2></div><button type="button" onClick={onClose}><X/></button></div><label>Date<input required name="date" type="date" defaultValue="2026-09-22"/></label><label>Merchant<input required name="merchant" placeholder="e.g. Local Grocer"/></label><label>Ultimate company<input required name="company" placeholder="Who ultimately receives it?"/></label><div className="form-row"><label>Category<select name="category">{Object.keys(palette).map(x=><option key={x}>{x}</option>)}</select></label><label>Amount (AUD)<input required name="amount" type="number" min="0.01" step="0.01" placeholder="0.00"/></label></div><label className="check"><input type="checkbox" name="recurring"/>This is a recurring payment</label><button className="submit" type="submit">Add to MoneyGraph</button><small>Your data stays in this browser. Nothing is sent to a server.</small></form></div>}
